### ISSUE TITLE
unable to buy items from shops

### ISSUE THREAD

**Issue by Papaturts** [Caltinor/DiceMC-Money-Mod#28]
Cureently unable to buy items from player shops while in ftb claimed chunks
Able to once the player is allied/part of the team
Any ideas on a work around for this?
mods list
![ice_screenshot_20220622-123429](https://user-images.githubusercontent.com/97408568/175101339-d0036a19-9a72-4cb0-b517-e5f54864d122.png)
![ice_screenshot_20220622-123452](https://user-images.githubusercontent.com/97408568/175101341-d8822bf2-245a-46f9-ac21-75e416e2fe2e.png)
![ice_screenshot_20220622-123506](https://user-images.githubusercontent.com/97408568/175101342-8b37af50-ce42-414e-8d04-fa954a34b5aa.png)

Any help would be greatly appreciated

**Comment by Caltinor** [comment]
This is a FTB Claims issue.  You need to find a way to let players interact with signs through that mod.  From my understanding FTB Claims is very restrictive and I personally recommend using Flan (Forge) instead since it has better configuration and has compat with this mod for buying claim blocks.
